# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StagesProgressIndicator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StagesProgressIndicator

  target 'StagesProgressIndicatorTests' do
    # Pods for testing
  end

end
